- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include_vars: variables/docker.yml
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml