- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include_vars: variables/docker_variables.yml
    - include_vars: variables/drive_variables.yml
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/mount-drives.yml
    - include: tasks/docker-star-apps.yml
    - include: tasks/cron.yml
#    - include: tasks/working_dir.yml