- name: Create folder for docker compose   
  file:
    path: /home/downloader/docker-compose      
    state: directory
    recurse: yes
  become: yes
  become_user: downloader

- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/downloader/docker-compose/docker-compose.yml
    owner: downloader
    group: downloader

- name: Run docker-compose up
  shell: docker-compose up
  args:
    chdir: /home/downloader/docker-compose