- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/downloader/docker-compose
    state: directory
    mode: '0755'

- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/downloader/docker-compose/docker-compose.yml
    owner: downloader
    group: dpwnloader

- name: Start containers
  docker_compose:
    project_src: /home/downloader/docker-compose/docker-compose.yml
    state: present
    compose_files:
      - /home/downloader/docker-compose/docker-compose.yml