- name: Create folder for docker compose   
  file:
    path: /home/downloader/docker-compose      
    state: directory
    recurse: yes
  become: yes
  become_user: downloader

- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/downloader/docker-compose/docker-compose.yml
    owner: downloader
    group: downloader

- name: Start containers
  docker_compose:
    project_src: /home/downloader/docker-compose/docker-compose.yml
    state: present
    compose_files:
      - /home/downloader/docker-compose/docker-compose.yml