- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/downloaders/docker-compose/docker-compose.yml
    owner: root
    group: root

- name: Start containers
  docker_compose:
    project_src: /home/downloader/docker-compose/docker-compose.yml
    state: present
    compose_files:
      - /home/downloader/docker-compose/docker-compose.yml