- name: create ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: crate downloader user
  user:
    name: downloader
    uid: 2003
    createhome: yes
    home: /home/downloader

- name: copy sudoers_downloader
  copy:
    src: files/sudoers_downloader
    dest: /etc/sudoers.d/downloader
    owner: root
    group: root
    mode: 0440